name: exif_reader
version: 3.17.0
description: Decode EXIF data from image files (improved fork of https://github.com/bigflood/dartexif). Supports VM, JavaScript and Web Assembly.
homepage: https://www.github.com/mgenware/exif_reader
environment:
  sdk: "^3.4.0"
dependencies:
  collection: ^1.15.0
  brotli: ^0.6.0
  iso_base_media: ^5.2.0
  sprintf: ^7.0.0
  js_interop_utils: ^1.0.8
  web: ^1.1.1
dev_dependencies:
  mgenware_dart_lints: ^8.1.0
  test: ^1.16.8
